import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NavBar } from "./components/navBar";
import { Footer } from "./components/footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'E-Commerce PabloKampmann',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-gray-700 flex flex-col min-h-screen`}>
        <NavBar></NavBar>
        <main className="flex-grow">{children}</main>
        <Footer></Footer>
      </body>
    </html>
  )
}
